name: Github Pages Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        working-directory: ./vuetube
        run: npm install
      
      - name: Build angular project
        working-directory: ./vuetube
        run: npm run build:prod
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: vuetube/dist/vuetube # The folder the action should deploy.        
